/* Automatically generated by './build/bin/build-entry.js' */

import Table from '../packages/table/index.js';
import TableColumn from '../packages/table-column/index.js';
import Tooltip from '../packages/tooltip/index.js';
import MessageBox from '../packages/message-box/index.js';
import Notification from '../packages/notification/index.js';
import Loading from '../packages/loading/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import Message from '../packages/message/index.js';
import ColorPicker from '../packages/color-picker/index.js';
import locale from 'element-ui/src/locale';
import CollapseTransition from 'element-ui/src/transitions/collapse-transition';
import Input from '../packages/input/index.js';
import Autocomplete from '../packages/autocomplete/index.js';

const components = [
  Table,
  TableColumn,
  Tooltip,
  Scrollbar,
  ColorPicker,
  CollapseTransition,
  Input,
  Autocomplete
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(Loading.directive);

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

module.exports = {
  version: '2.4.5',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Table,
  TableColumn,
  Tooltip,
  MessageBox,
  Notification,
  Scrollbar,
  Message,
  ColorPicker
};

module.exports.default = module.exports;
